name: variables and secrets
wnv:
WF_VAR: "workflow level variable"
on:
  push:
jobs:
  test_variables:
  env:
    JOB_VAR: " job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      -name: test varibles
      id: stepvar
      run:
        echo ${{ github.actor}}
        echo $GITHUB_JOB
        echo $WF_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo ${{ vars.CONF_VAR}}
        echo ${{ secrets.A_SECRET}}

        
